package pt.enta;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App extends javax.swing.JFrame {

    ArrayList<Formandos> arrayFormandos = new ArrayList<>();
    ArrayList<Cursos> arrayCursos = new ArrayList<>();
    ArrayList<Disciplinas> arrayDisciplinas = new ArrayList<>();
    ArrayList<CursosDisciplina> arrayCursosDisciplinas = new ArrayList<>();
    ArrayList<Candidaturas> arrayCandidaturas = new ArrayList<>();

    Random random = new Random();

    public App() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        btnFormandos = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        btnDisciplinas = new javax.swing.JButton();
        btnDiscCurso = new javax.swing.JButton();
        btnCandidaturas = new javax.swing.JButton();
        SecondMenu = new javax.swing.JFrame();
        lblTitle = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        InserirFormando = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeFormando = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idade = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        rdMasculino = new javax.swing.JRadioButton();
        rdFeminimo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        numTel = new javax.swing.JTextField();
        btnInserirFormando = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Listar = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFormandos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCursos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDisciplinas = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaDiscCurso = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaCandidaturas = new javax.swing.JTextArea();
        InserirCurso = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nomeCurso = new javax.swing.JTextField();
        totalHorasCurso = new javax.swing.JTextField();
        btnInserirCurso = new javax.swing.JButton();
        lblIDCurso = new javax.swing.JLabel();
        nVagas = new javax.swing.JTextField();
        nDisciplinas = new javax.swing.JTextField();
        InserirDisciplinas = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nomeDisciplina = new javax.swing.JTextField();
        totalHorasDisciplina = new javax.swing.JTextField();
        lblIDDisciplina = new javax.swing.JLabel();
        btnInserirDisciplina = new javax.swing.JButton();
        InserirDisciplinaCurso = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbDisciplina = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        InserirCandidatura = new javax.swing.JFrame();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblIdMatricula = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nomeCandidato = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cbCursoCandidato = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        InseridoSucesso = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        comboBoxEmpty = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnRestaurarListas = new javax.swing.JButton();

        MainMenu.setTitle("School");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Menu Principal");

        btnFormandos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFormandos.setText("Formandos");
        btnFormandos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormandosActionPerformed(evt);
            }
        });

        btnCursos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCursos.setText("Cursos");
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });

        btnDisciplinas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDisciplinas.setText("Disciplinas");
        btnDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinasActionPerformed(evt);
            }
        });

        btnDiscCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDiscCurso.setText("Disciplinas de Curso");
        btnDiscCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscCursoActionPerformed(evt);
            }
        });

        btnCandidaturas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCandidaturas.setText("Candidaturas");
        btnCandidaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidaturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu.getContentPane());
        MainMenu.getContentPane().setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainMenuLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFormandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDiscCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCandidaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(btnFormandos)
                .addGap(18, 18, 18)
                .addComponent(btnCursos)
                .addGap(18, 18, 18)
                .addComponent(btnDisciplinas)
                .addGap(18, 18, 18)
                .addComponent(btnDiscCurso)
                .addGap(18, 18, 18)
                .addComponent(btnCandidaturas)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        btnInserir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SecondMenuLayout = new javax.swing.GroupLayout(SecondMenu.getContentPane());
        SecondMenu.getContentPane().setLayout(SecondMenuLayout);
        SecondMenuLayout.setHorizontalGroup(
            SecondMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondMenuLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(SecondMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInserir, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SecondMenuLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        SecondMenuLayout.setVerticalGroup(
            SecondMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnInserir)
                .addGap(18, 18, 18)
                .addComponent(btnListar)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Inserir Formando");

        jLabel4.setText("ID:");

        jLabel5.setText("Nome:");

        jLabel6.setText("Idade:");

        idade.setModel(new javax.swing.SpinnerNumberModel(15, 15, 30, 1));

        jLabel7.setText("Género:");

        buttonGroup1.add(rdMasculino);
        rdMasculino.setText("Masculino");

        buttonGroup1.add(rdFeminimo);
        rdFeminimo.setText("Feminimo");

        jLabel8.setText("Número de telemóvel / telefone:");

        btnInserirFormando.setText("Inserir");
        btnInserirFormando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirFormandoActionPerformed(evt);
            }
        });

        lblID.setText("0");

        javax.swing.GroupLayout InserirFormandoLayout = new javax.swing.GroupLayout(InserirFormando.getContentPane());
        InserirFormando.getContentPane().setLayout(InserirFormandoLayout);
        InserirFormandoLayout.setHorizontalGroup(
            InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirFormandoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirFormandoLayout.createSequentialGroup()
                        .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InserirFormandoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InserirFormandoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(rdMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdFeminimo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InserirFormandoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numTel))
                            .addGroup(InserirFormandoLayout.createSequentialGroup()
                                .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeFormando, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirFormandoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirFormandoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirFormandoLayout.createSequentialGroup()
                                .addComponent(btnInserirFormando, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        InserirFormandoLayout.setVerticalGroup(
            InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirFormandoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomeFormando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rdMasculino)
                    .addComponent(rdFeminimo))
                .addGap(18, 18, 18)
                .addGroup(InserirFormandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(numTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnInserirFormando)
                .addGap(23, 23, 23))
        );

        listaFormandos.setColumns(20);
        listaFormandos.setRows(5);
        jScrollPane1.setViewportView(listaFormandos);

        listaCursos.setColumns(20);
        listaCursos.setRows(5);
        jScrollPane2.setViewportView(listaCursos);

        listaDisciplinas.setColumns(20);
        listaDisciplinas.setRows(5);
        jScrollPane3.setViewportView(listaDisciplinas);

        listaDiscCurso.setColumns(20);
        listaDiscCurso.setRows(5);
        jScrollPane4.setViewportView(listaDiscCurso);

        listaCandidaturas.setColumns(20);
        listaCandidaturas.setRows(5);
        jScrollPane5.setViewportView(listaCandidaturas);

        javax.swing.GroupLayout ListarLayout = new javax.swing.GroupLayout(Listar.getContentPane());
        Listar.getContentPane().setLayout(ListarLayout);
        ListarLayout.setHorizontalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        ListarLayout.setVerticalGroup(
            ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("Inserir Curso");

        jLabel10.setText("ID:");

        jLabel11.setText("Nome do Curso:");

        jLabel12.setText("Total de Horas:");

        jLabel13.setText("Nº de Vagas:");

        jLabel14.setText("Nº de Disciplinas:");

        btnInserirCurso.setText("Inserir");
        btnInserirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirCursoActionPerformed(evt);
            }
        });

        lblIDCurso.setText("0");

        javax.swing.GroupLayout InserirCursoLayout = new javax.swing.GroupLayout(InserirCurso.getContentPane());
        InserirCurso.getContentPane().setLayout(InserirCursoLayout);
        InserirCursoLayout.setHorizontalGroup(
            InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirCursoLayout.createSequentialGroup()
                .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirCursoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCurso)
                            .addGroup(InserirCursoLayout.createSequentialGroup()
                                .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalHorasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(InserirCursoLayout.createSequentialGroup()
                        .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirCursoLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel9))
                            .addGroup(InserirCursoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InserirCursoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(nDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirCursoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInserirCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(InserirCursoLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblIDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InserirCursoLayout.setVerticalGroup(
            InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lblIDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(totalHorasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InserirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInserirCurso)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("Inserir Disciplina");

        jLabel16.setText("ID:");

        jLabel17.setText("Nome da Disciplina:");

        jLabel18.setText("Total de Horas da Disciplina:");

        lblIDDisciplina.setText("0");

        btnInserirDisciplina.setText("Inserir");
        btnInserirDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InserirDisciplinasLayout = new javax.swing.GroupLayout(InserirDisciplinas.getContentPane());
        InserirDisciplinas.getContentPane().setLayout(InserirDisciplinasLayout);
        InserirDisciplinasLayout.setHorizontalGroup(
            InserirDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirDisciplinasLayout.createSequentialGroup()
                .addGroup(InserirDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirDisciplinasLayout.createSequentialGroup()
                        .addGroup(InserirDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirDisciplinasLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InserirDisciplinasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIDDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(InserirDisciplinasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InserirDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirDisciplinasLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeDisciplina))
                            .addGroup(InserirDisciplinasLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalHorasDisciplina))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirDisciplinasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInserirDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        InserirDisciplinasLayout.setVerticalGroup(
            InserirDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirDisciplinasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(InserirDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblIDDisciplina))
                .addGap(18, 18, 18)
                .addGroup(InserirDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(nomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InserirDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(totalHorasDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnInserirDisciplina)
                .addContainerGap())
        );

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setText("Inserir disciplinas nos cursos");

        jLabel20.setText("Curso: ");

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel21.setText("Disciplina:");

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InserirDisciplinaCursoLayout = new javax.swing.GroupLayout(InserirDisciplinaCurso.getContentPane());
        InserirDisciplinaCurso.getContentPane().setLayout(InserirDisciplinaCursoLayout);
        InserirDisciplinaCursoLayout.setHorizontalGroup(
            InserirDisciplinaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirDisciplinaCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InserirDisciplinaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirDisciplinaCursoLayout.createSequentialGroup()
                        .addGroup(InserirDisciplinaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InserirDisciplinaCursoLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(InserirDisciplinaCursoLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirDisciplinaCursoLayout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirDisciplinaCursoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        InserirDisciplinaCursoLayout.setVerticalGroup(
            InserirDisciplinaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirDisciplinaCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(InserirDisciplinaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(InserirDisciplinaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel22.setText("Candidatura");

        jLabel23.setText("Matrícula:");

        jLabel24.setText("Nome:");

        jLabel25.setText("Curso:");

        jButton2.setText("Candidatar-me");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InserirCandidaturaLayout = new javax.swing.GroupLayout(InserirCandidatura.getContentPane());
        InserirCandidatura.getContentPane().setLayout(InserirCandidaturaLayout);
        InserirCandidaturaLayout.setHorizontalGroup(
            InserirCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirCandidaturaLayout.createSequentialGroup()
                .addGroup(InserirCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirCandidaturaLayout.createSequentialGroup()
                        .addGroup(InserirCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirCandidaturaLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel22))
                            .addGroup(InserirCandidaturaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(InserirCandidaturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InserirCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirCandidaturaLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeCandidato))
                            .addGroup(InserirCandidaturaLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCursoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 118, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirCandidaturaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        InserirCandidaturaLayout.setVerticalGroup(
            InserirCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirCandidaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(InserirCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblIdMatricula))
                .addGap(18, 18, 18)
                .addGroup(InserirCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(nomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InserirCandidaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cbCursoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setText("Os campos são de preenchimento obrigatório! ");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(83, 83, 83))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel26)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel27.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel27.setText("Inserido com sucesso ! ");

        javax.swing.GroupLayout InseridoSucessoLayout = new javax.swing.GroupLayout(InseridoSucesso.getContentPane());
        InseridoSucesso.getContentPane().setLayout(InseridoSucessoLayout);
        InseridoSucessoLayout.setHorizontalGroup(
            InseridoSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InseridoSucessoLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        InseridoSucessoLayout.setVerticalGroup(
            InseridoSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InseridoSucessoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel27)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Neste momento ainda não existem disciplinas/ cursos introduzidos ! ");

        javax.swing.GroupLayout comboBoxEmptyLayout = new javax.swing.GroupLayout(comboBoxEmpty.getContentPane());
        comboBoxEmpty.getContentPane().setLayout(comboBoxEmptyLayout);
        comboBoxEmptyLayout.setHorizontalGroup(
            comboBoxEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboBoxEmptyLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 357, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        comboBoxEmptyLayout.setVerticalGroup(
            comboBoxEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboBoxEmptyLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel28)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School");
        setBackground(new java.awt.Color(255, 153, 153));
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Bem-vindo à Escola");

        btnMenu.setBackground(new java.awt.Color(204, 204, 255));
        btnMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(204, 204, 255));
        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnRestaurarListas.setText("Restaurar");
        btnRestaurarListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarListasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRestaurarListas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnRestaurarListas)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_btnSairActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        MainMenu.setVisible(true);
        MainMenu.setSize(450, 400);
        MainMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnFormandosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormandosActionPerformed
        // TODO add your handling code here:
        SecondMenu.setVisible(true);
        SecondMenu.setSize(450, 400);
        SecondMenu.setLocationRelativeTo(null);
        lblTitle.setText(btnFormandos.getText());
    }//GEN-LAST:event_btnFormandosActionPerformed

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
        // TODO add your handling code here:
        SecondMenu.setVisible(true);
        SecondMenu.setSize(450, 400);
        SecondMenu.setLocationRelativeTo(null);
        lblTitle.setText(btnCursos.getText());
    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinasActionPerformed
        // TODO add your handling code here:
        SecondMenu.setVisible(true);
        SecondMenu.setSize(450, 400);
        SecondMenu.setLocationRelativeTo(null);
        lblTitle.setText(btnDisciplinas.getText());
    }//GEN-LAST:event_btnDisciplinasActionPerformed

    private void btnDiscCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscCursoActionPerformed
        // TODO add your handling code here:
        SecondMenu.setVisible(true);
        SecondMenu.setSize(450, 400);
        SecondMenu.setLocationRelativeTo(null);
        lblTitle.setText(btnDiscCurso.getText());
    }//GEN-LAST:event_btnDiscCursoActionPerformed

    private void btnCandidaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidaturasActionPerformed
        // TODO add your handling code here:
        SecondMenu.setVisible(true);
        SecondMenu.setSize(450, 400);
        SecondMenu.setLocationRelativeTo(null);
        lblTitle.setText(btnCandidaturas.getText());
    }//GEN-LAST:event_btnCandidaturasActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        Listar.setVisible(true);
        Listar.setSize(600, 650);
        Listar.setLocationRelativeTo(null);

        if (arrayCursos.isEmpty()) {

        } else {
            listaCursos.setText("");
            for (Cursos c : arrayCursos) {
                listaCursos.append(c.toString() + "\n");
            }

        }

        if (arrayFormandos.isEmpty()) {

        } else {
            listaFormandos.setText("");
            for (Formandos f : arrayFormandos) {
                listaFormandos.append(f.toString() + "\n");
            }
        }

        if (arrayDisciplinas.isEmpty()) {

        } else {
            listaDisciplinas.setText("");
            for (Disciplinas d : arrayDisciplinas) {
                listaDisciplinas.append(d.toString() + "\n");
            }
        }

        if (arrayCursosDisciplinas.isEmpty()) {

        } else {
            listaDiscCurso.setText("");
            for (CursosDisciplina cd : arrayCursosDisciplinas) {
                listaDiscCurso.append(cd.toString() + "\n");
            }
        }

        if (arrayCandidaturas.isEmpty()) {

        } else {
            listaCandidaturas.setText("");
            for (Candidaturas can : arrayCandidaturas) {
                listaCandidaturas.append(can.toString() + "\n");
            }
        }


    }//GEN-LAST:event_btnListarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:

        if (lblTitle.getText().equals("Formandos")) {

            InserirFormando.setVisible(true);
            InserirFormando.setSize(450, 400);
            InserirFormando.setLocationRelativeTo(null);

        } else if (lblTitle.getText().equals("Cursos")) {

            InserirCurso.setVisible(true);
            InserirCurso.setSize(450, 400);
            InserirCurso.setLocationRelativeTo(null);

        } else if (lblTitle.getText().equals("Disciplinas")) {

            InserirDisciplinas.setVisible(true);
            InserirDisciplinas.setSize(450, 400);
            InserirDisciplinas.setLocationRelativeTo(null);

        } else if (lblTitle.getText().equals("Disciplinas de Curso")) {

            if (cbCurso.getItemCount() == 0 || cbDisciplina.getItemCount() == 0) {
                comboBoxEmpty.setVisible(true);
                comboBoxEmpty.setSize(400, 200);
                comboBoxEmpty.setLocationRelativeTo(null);
            } else {
                InserirDisciplinaCurso.setVisible(true);
                InserirDisciplinaCurso.setSize(450, 200);
                InserirDisciplinaCurso.setLocationRelativeTo(null);
            }

        } else {
            if (cbCursoCandidato.getItemCount() == 0) {
                comboBoxEmpty.setVisible(true);
                comboBoxEmpty.setSize(400, 200);
                comboBoxEmpty.setLocationRelativeTo(null);
                jLabel28.setText("Não existem cursos disponiveis!");
            } else {
                InserirCandidatura.setVisible(true);
                InserirCandidatura.setSize(450, 300);
                InserirCandidatura.setLocationRelativeTo(null);
                lblIdMatricula.setText(String.valueOf(random.nextInt(2000) + 1));
            }

        }


    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnInserirFormandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirFormandoActionPerformed
        // TODO add your handling code here:

        int idFormando = Integer.parseInt(lblID.getText());

        if (nomeFormando.getText().isEmpty() || numTel.getText().isEmpty()) {

            jDialog1.setVisible(true);
            jDialog1.setSize(400, 200);
            jDialog1.setLocationRelativeTo(null);
            nomeFormando.setText("");
            numTel.setText("");

        } else {

            if (rdMasculino.isSelected()) {
                idFormando++;
                lblID.setText(String.valueOf(idFormando));
                Formandos formandos = new Formandos();
                
                formandos.setId(Integer.parseInt(lblID.getText()));
                formandos.setNome(nomeFormando.getText());
                formandos.setAge((int) idade.getValue());
                formandos.setGenero(rdMasculino.getText());
                formandos.setTelemovel(Integer.parseInt(numTel.getText()));

                InseridoSucesso.setVisible(true);
                InseridoSucesso.setSize(400, 200);
                InseridoSucesso.setLocationRelativeTo(null);

                try {
                    arrayFormandos.add(formandos);
                    FileOutputStream fileOutputStream = new FileOutputStream("C:\\new\\formandos.txt");
                    try ( ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                        objectOutputStream.writeObject(arrayFormandos);
                        objectOutputStream.close();
                        fileOutputStream.close();
                    } catch (IOException ex) {
                        Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                idFormando++;
                lblID.setText(String.valueOf(idFormando));
                Formandos formandos = new Formandos();
                
                formandos.setId(Integer.parseInt(lblID.getText()));
                formandos.setNome(nomeFormando.getText());
                formandos.setAge((int) idade.getValue());
                formandos.setGenero(rdFeminimo.getText());
                formandos.setTelemovel(Integer.parseInt(numTel.getText()));

                InseridoSucesso.setVisible(true);
                InseridoSucesso.setSize(400, 200);
                InseridoSucesso.setLocationRelativeTo(null);

                try {
                    arrayFormandos.add(formandos);
                    FileOutputStream fileOutputStream = new FileOutputStream("C:\\new\\formandos.txt");
                    try ( ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                        objectOutputStream.writeObject(arrayFormandos);
                        objectOutputStream.close();
                        fileOutputStream.close();
                    } catch (IOException ex) {
                        Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
                listaFormandos.setText("");
            }

        }


    }//GEN-LAST:event_btnInserirFormandoActionPerformed

    private void btnInserirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirCursoActionPerformed
        // TODO add your handling code here:

        int iddoCurso = Integer.parseInt(lblIDCurso.getText());

        if (nomeCurso.getText().isEmpty() || totalHorasCurso.getText().isEmpty() || nVagas.getText().isEmpty() || nDisciplinas.getText().isEmpty()) {
            jDialog1.setVisible(true);
            jDialog1.setSize(400, 200);
            jDialog1.setLocationRelativeTo(null);
            nomeCurso.setText("");
            totalHorasCurso.setText("");
            nVagas.setText("");
            nDisciplinas.setText("");

        } else {
            iddoCurso++;
            lblIDCurso.setText(String.valueOf(iddoCurso));
            Cursos cursos = new Cursos();
            
            cursos.setId(Integer.parseInt(lblIDCurso.getText()));
            cursos.setNome(nomeCurso.getText());
            cursos.setNumVagas(Integer.parseInt(nDisciplinas.getText()));
            cursos.setNumDisciplinas(Integer.parseInt(nDisciplinas.getText()));
            cursos.setTotalHoras(Integer.parseInt(totalHorasCurso.getText()));

            cbCurso.addItem(nomeCurso.getText());
            cbCursoCandidato.addItem(nomeCurso.getText());

            InseridoSucesso.setVisible(true);
            InseridoSucesso.setSize(400, 200);
            InseridoSucesso.setLocationRelativeTo(null);

            try {
                arrayCursos.add(cursos);
                FileOutputStream fileOutputStream = new FileOutputStream("C:\\new\\cursos.txt");
                try ( ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                    objectOutputStream.writeObject(arrayCursos);
                    objectOutputStream.close();
                    fileOutputStream.close();
                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
            listaCursos.setText("");
        }


    }//GEN-LAST:event_btnInserirCursoActionPerformed

    private void btnInserirDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirDisciplinaActionPerformed
        // TODO add your handling code here:
        int iddaDisciplina = Integer.parseInt(lblIDDisciplina.getText());

        if (nomeDisciplina.getText().isEmpty() || totalHorasDisciplina.getText().isEmpty()) {
            jDialog1.setVisible(true);
            jDialog1.setSize(400, 200);
            jDialog1.setLocationRelativeTo(null);
            nomeDisciplina.setText("");
            totalHorasDisciplina.setText("");
        } else {
            iddaDisciplina++;
            lblIDDisciplina.setText(String.valueOf(iddaDisciplina));
            Disciplinas disciplinas = new Disciplinas();
            disciplinas.setId(Integer.parseInt(lblIDDisciplina.getText()));
            disciplinas.setNome(nomeDisciplina.getText());
            disciplinas.setTotalHoras(Integer.parseInt(totalHorasDisciplina.getText()));

            cbDisciplina.addItem(nomeDisciplina.getText());

            InseridoSucesso.setVisible(true);
            InseridoSucesso.setSize(400, 200);
            InseridoSucesso.setLocationRelativeTo(null);

            try {
                arrayDisciplinas.add(disciplinas);
                FileOutputStream fileOutputStream = new FileOutputStream("C:\\new\\disciplinas.txt");
                try ( ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                    objectOutputStream.writeObject(arrayDisciplinas);
                    objectOutputStream.close();
                    fileOutputStream.close();
                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
            listaDisciplinas.setText("");
        }


    }//GEN-LAST:event_btnInserirDisciplinaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CursosDisciplina cursosdisciplina = new CursosDisciplina();

        cursosdisciplina.setNomeDoCurso((String) cbCurso.getSelectedItem());
        cursosdisciplina.setNomeDaDisciplina((String) cbDisciplina.getSelectedItem());

        InseridoSucesso.setVisible(true);
        InseridoSucesso.setSize(400, 200);
        InseridoSucesso.setLocationRelativeTo(null);

        try {
            arrayCursosDisciplinas.add(cursosdisciplina);
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\new\\cursosedisciplinas.txt");
            try ( ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(arrayCursosDisciplinas);
                objectOutputStream.close();
                fileOutputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        listaDiscCurso.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Candidaturas candidaturas = new Candidaturas();

        candidaturas.setIdMatricula(Integer.parseInt(lblIdMatricula.getText()));
        candidaturas.setNomeCandidato(nomeCandidato.getText());
        candidaturas.setNomeCurso((String) cbCursoCandidato.getSelectedItem());

        nomeCandidato.setText("");
        cbCursoCandidato.setSelectedIndex(0);
        lblIdMatricula.setText(String.valueOf(random.nextInt(2000) + 1));

        InseridoSucesso.setVisible(true);
        InseridoSucesso.setSize(400, 200);
        InseridoSucesso.setLocationRelativeTo(null);

        try {
            arrayCandidaturas.add(candidaturas);
            FileOutputStream fileOutputStream = new FileOutputStream("C:\\new\\candidaturas.txt");
            try ( ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(arrayCandidaturas);
                objectOutputStream.close();
                fileOutputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        listaCandidaturas.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRestaurarListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarListasActionPerformed
        // TODO add your handling code here:

        try {
            FileInputStream fileInputStream = new FileInputStream("C:\\new\\cursos.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            arrayCursos = (ArrayList) objectInputStream.readObject();
            objectInputStream.close();
            fileInputStream.close();

        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        }

        try {
            FileInputStream fileInputStream = new FileInputStream("C:\\new\\formandos.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            arrayFormandos = (ArrayList) objectInputStream.readObject();
            objectInputStream.close();
            fileInputStream.close();

        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        }

        try {
            FileInputStream fileInputStream = new FileInputStream("C:\\new\\disciplinas.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            arrayDisciplinas = (ArrayList) objectInputStream.readObject();
            objectInputStream.close();
            fileInputStream.close();

        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        }

        try {
            FileInputStream fileInputStream = new FileInputStream("C:\\new\\cursosedisciplinas.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            arrayCursosDisciplinas = (ArrayList) objectInputStream.readObject();
            objectInputStream.close();
            fileInputStream.close();

        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        }

        try {
            FileInputStream fileInputStream = new FileInputStream("C:\\new\\candidaturas.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            arrayCandidaturas = (ArrayList) objectInputStream.readObject();
            objectInputStream.close();
            fileInputStream.close();

        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        }


    }//GEN-LAST:event_btnRestaurarListasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog InseridoSucesso;
    private javax.swing.JFrame InserirCandidatura;
    private javax.swing.JFrame InserirCurso;
    private javax.swing.JFrame InserirDisciplinaCurso;
    private javax.swing.JFrame InserirDisciplinas;
    private javax.swing.JFrame InserirFormando;
    private javax.swing.JFrame Listar;
    private javax.swing.JFrame MainMenu;
    private javax.swing.JFrame SecondMenu;
    private javax.swing.JButton btnCandidaturas;
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnDiscCurso;
    private javax.swing.JButton btnDisciplinas;
    private javax.swing.JButton btnFormandos;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnInserirCurso;
    private javax.swing.JButton btnInserirDisciplina;
    private javax.swing.JButton btnInserirFormando;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRestaurarListas;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JComboBox<String> cbCursoCandidato;
    private javax.swing.JComboBox<String> cbDisciplina;
    private javax.swing.JDialog comboBoxEmpty;
    private javax.swing.JSpinner idade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDCurso;
    private javax.swing.JLabel lblIDDisciplina;
    private javax.swing.JLabel lblIdMatricula;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea listaCandidaturas;
    private javax.swing.JTextArea listaCursos;
    private javax.swing.JTextArea listaDiscCurso;
    private javax.swing.JTextArea listaDisciplinas;
    private javax.swing.JTextArea listaFormandos;
    private javax.swing.JTextField nDisciplinas;
    private javax.swing.JTextField nVagas;
    private javax.swing.JTextField nomeCandidato;
    private javax.swing.JTextField nomeCurso;
    private javax.swing.JTextField nomeDisciplina;
    private javax.swing.JTextField nomeFormando;
    private javax.swing.JTextField numTel;
    private javax.swing.JRadioButton rdFeminimo;
    private javax.swing.JRadioButton rdMasculino;
    private javax.swing.JTextField totalHorasCurso;
    private javax.swing.JTextField totalHorasDisciplina;
    // End of variables declaration//GEN-END:variables

}
